version: "3.8"
services:
  php:
    build:
      dockerfile: etc/artifacts/Dockerfile
      context: .
      target: dev
    ports:
      - "9000:9000"
    environment:
      - XDEBUG_CLIENT_HOST=host.docker.internal
    volumes:
      - ./:/app:rw,delegated
      # If you're using Linux you can comment out volumes below
      - /app/var/
      - /app/var/cache/
      - /app/var/logs/
      - /app/var/sessions/
